export const captions = [
  "Entrata del parco bisonte romolo",
  "Entrata del parco elefante sabè",
  "Entrata del parco inaugurazione sotto la pioggia",
  "Entrata del parco ippopotamo abai",
  "Rettilario",
  "Fossa delle scimmie",
  "Vasca delle otarie",
  "Gabbia delle tigri",
  "Gabbie delle tigri",
  "Gabbie delle tigri-1",
  "Gabbie delle tigri-2",
  "Zona edificio accanto al rettilario taz",
  "Foto viale ginkgo biloba",
  "Chiusura zoo",
  "Chiusura zoo-1",
  "Lo zoo del michelotti riapre zona",
  "Img 20231019 142033",
  "Img 20231019 wa0021",
];
