/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://evqb74ixorgr7fszphgkp23h6y.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7od4eb7ylrhtlm33ppcfmgzvea",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true,
    "aws_cognito_identity_pool_id": "eu-central-1:bd901e11-8ab3-46f0-9025-871581df66e8",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_A3bO9YENs",
    "aws_user_pools_web_client_id": "4nonodqh2bdkdr8qqkuadrfmbu",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS",
        "TOTP"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "seetizen-storage-bucket94749-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
