/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "eu-central-1",
  aws_cognito_identity_pool_id:
    "eu-central-1:6246f2a7-4601-4374-a410-f034ee90c88c",
  aws_cognito_region: "eu-central-1",
  aws_user_pools_id: "eu-central-1_wRfU1oFYf",
  aws_user_pools_web_client_id: "7finpjqecq58ad6jip1p6ma65d",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["PHONE_NUMBER"],
  aws_cognito_mfa_configuration: "OPTIONAL",
  aws_cognito_mfa_types: ["SMS", "TOTP"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_appsync_graphqlEndpoint:
    "https://mlwveuhnkjhrrb5mfbwj2h4r4u.appsync-api.eu-central-1.amazonaws.com/graphql",
  aws_appsync_region: "eu-central-1",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "da2-xfx7izkjlbh3tcpb5y6akq2h4a",
  aws_user_files_s3_bucket:
    "seetizen142f36cda8a7417cae3efe1229e5f1f8183740-dev",
  aws_user_files_s3_bucket_region: "eu-central-1",
};

export default awsmobile;
